theme:
  background-color: white
  text-color: black

header:
  text:
    An official website of the United States government 

content:
  left:
    text:
      <strong>Official websites use .gov</strong><br>
      A .gov website belongs to an official government organization in the United States. 
  right:
    text:
      <strong>Secure .gov websites use HTTPS</strong><br>
      A lock (🔒) or https:// means you've safely connected to the .gov website. Share sensitive information only on official, secure websites.